language: ruby
rvm:
  - 2.2.1
env:
  - DB=postgresql
script:
- export RAILS_ENV=test
- bundle exec rake db:create db:schema:load db:test:prepare
- bundle exec rspec
before_script:
  - psql -c 'create database assignment_angular_rails_crud_test' -U postgres